spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:7200/security
    username: dusabe
    password: rdowssap
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
